### ISSUE TITLE
Lithium fabric crashed the game

### ISSUE THREAD

**Issue by kashy123** [1qwaka/Thorium-Evolution-6.0#1]
I'm playing on mobile And Thought I might try out your new material see how it changed the game but the Moment I built the lithium fabric factory it crashed Just in case it was a fluke I tried again 3 times still crashed please fix this

**Comment by 1qwaka** [comment]
I suppose you mean 'radium fabric'. because the mod doesn't have 'lithium fabric'. 
fixed radium fabric game crashing
